#pragma config(Motor,  port1,           LDrive1,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LDrive2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RDrive1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RDrive2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           chainBar,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rollers,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mobileGoal1,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mobileGoal2,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          lift2,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#region setup
#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
#include "Includes\pd_autoMove.c"
//#endregion

//#region buttons
	//#subregion mobile goal
#define mobileGoalInBtn   Btn6U
#define mobileGoalOutBtn	Btn6D
	//#endsubregion
  //#subregion
#define stackBtn Btn5U
  //#endsubregion
//#endregion

//#region constants

//#endregion

void pre_auton() {

}
