#pragma config(Sensor, in1,    liftSensor,     sensorPotentiometer)
#pragma config(Sensor, in2,    goalSensor,     sensorPotentiometer)
#pragma config(Sensor, in3,    goalFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEnc,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEnc,        sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  fbSol,          sensorDigitalOut)
#pragma config(Sensor, dgtl6,  intakeSol,      sensorDigitalOut)
#pragma config(Motor,  port1,           LDrive1,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LSwitchy,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LDrive2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           lift1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           lift2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           lift3,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           lift4,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           RDrive1,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RSwitchy,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          RDrive2,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

//#region includes
#include "Vex_Competition_Includes.c"
#include "../lib/buttonTracker.c"
#include "../lib/pneumaticGroup.c"
#include "../lib/parallelDrive.c"
//#endregion


//#region globals
motorGroup lift;
motorGroup goalIntake;

pneumaticGroup fourBar;
pneumaticGroup coneIntake;

parallel_drive drive;
//#endregion


void pre_auton()
{
  bStopTasksBetweenModes = true;

  tMotor LDriveMotors[] = { LDrive1, LDrive2, LSwitchy };
  tMotor RDriveMotors[] = { RDrive1, RDrive2, RSwitchy };
  initializeDrive(drive, 3, LDriveMotors, 3, RDriveMotors);

  tMotor liftMotors[] = { lift1, lift2, lift3, lift4 };
	initializeGroup(lift, 4, liftMotors, Btn5U, Btn5D, 10);
	configureBtnDependentStillSpeed(lift);

	tMotor goalMotors[] = { LSwitchy, RSwitchy };
	initializeGroup(goalIntake, 2, goalMotors, Btn7U, Btn7D);

	initializePneumaticGroup(coneIntake, intakeSol);
	configureToggleInput(coneIntake, Btn6U);

	initializePneumaticGroup(fourBar, fbSol);
	configureToggleInput(fourBar, Btn6D);
}

task autonomous() {
  AutonomousCodePlaceholderForTesting();
}

void updateMotorConfig(int goalPower) {
	if (goalPower != 0) {
		setNumMotors(drive, 2, 2);

		bool goalOut = goalPower > 0;
		setPowerLimits(drive, (goalOut ? -127 : -30), (goalOut ? 30 : 127));
	}
	else {
		setNumMotors(drive, 3, 3);
		stopPowerLimiting(drive);
	}
}

void handleGoalInput() {
	updateMotorConfig(takeInput(goalIntake));	//USE AUTOMOVEMENT QUALIFICATION FOR REAL CODE
}

task usercontrol() {
  while (true) {
  	handleGoalInput();

  	takeInput(lift);
  	takeInput(fourBar);
  	takeInput(coneIntake);
  	driveRuntime(drive);
  }
}
