#pragma config(Sensor, in1,    hyro,           sensorGyro)
#pragma config(Sensor, in2,    sidePot,        sensorPotentiometer)
#pragma config(Sensor, in3,    modePot,        sensorPotentiometer)
#pragma config(Sensor, in4,    liftSensor,     sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftEnc,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEnc,       sensorQuadEncoder)
#pragma config(Motor,  port1,           LDrive1,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LDrive2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LSwitchy,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           fbMotor,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rollerMotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RSwitchy,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RDrive1,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          RDrive2,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

//#region includes
#include "Vex_Competition_Includes.c"
#include "../lib/parallelDrive.c"
#include "../lib/buttonTracker.c"
//#endregion

#define FB_STILL_SPEED 10

//#region globals
bool fbIn = true;

motorGroup lift;
motorGroup coneIntake;
motorGroup goalIntake;
motorGroup fourBar;
parallel_drive drive;
//#endregion


void pre_auton()
{
  bStopTasksBetweenModes = true;

  tMotor LDriveMotors[] = { LDrive1, LDrive2, LSwitchy };
  tMotor RDriveMotors[] = { RDrive1, RDrive2, RSwitchy };
  initializeDrive(drive, 3, LDriveMotors, 3, RDriveMotors);

  tMotor liftMotors[] = { lift1, lift2 };
	initializeGroup(lift, 2, liftMotors, Btn5U, Btn5D, 10);
	configureBtnDependentStillSpeed(lift);

	tMotor goalMotors[] = { LSwitchy, RSwitchy };
	initializeGroup(goalIntake, 2, goalMotors, Btn7U, Btn7D);

	tMotor coneMotors[] = { rollerMotor };
	initializeGroup(coneIntake, 1, coneMotors, Btn6U, Btn6D, 15);

	tMotor fbMotors[] = { fbMotor };
	initializeGroup(fourBar, 1, fbMotors, Btn8U, Btn8D, FB_STILL_SPEED);
	configureBtnDependentStillSpeed(fourBar);
}

task autonomous() {
  AutonomousCodePlaceholderForTesting();
}

void updateMotorConfig(int goalPower) {
	if (goalPower != 0) {
		setNumMotors(drive, 2, 2);

		bool goalOut = goalPower > 0;
		setPowerLimits(drive, (goalOut ? -127 : -30), (goalOut ? 30 : 127));
	}
	else {
		setNumMotors(drive, 3, 3);
		stopPowerLimiting(drive);
	}
}

void handleGoalInput() {
	updateMotorConfig(takeInput(goalIntake));	//USE AUTOMOVEMENT QUALIFICATION FOR REAL CODE
}

void handleFbInput() {
	if (newlyPressed(Btn8L)) {
		fbIn = !fbIn;
		moveForDuration(fourBar, (fbIn ? -127 : 127), 500);
	}

	executeAutomovement(fourBar);

	int fbPower = takeInput(fourBar, fourBar.moving==NO);

	if (fabs(fbPower) > FB_STILL_SPEED)	//update fbUp
				fbIn = fbPower < 0;
}

task usercontrol() {
  while (true) {
  	handleFbInput();
  	handleGoalInput();

  	takeInput(lift);
  	takeInput(coneIntake);
  	driveRuntime(drive);
  }
}
