#pragma config(Motor,  port1,           LDrive1,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LSwitchy,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LDrive2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           lift1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           lift2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RDrive,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           lift3,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rollerMotor,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RSwitchy,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          fbMotor,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	int coeff;

	while (true) {
		coeff = 127 * (1 - 2*vexRT[Btn6U]);


		motor[port1] = vexRT[Btn5D] * coeff;
		motor[port2] = vexRT[Btn5U] * coeff;
		motor[port3] = vexRT[Btn7U] * coeff;
		motor[port4] = vexRT[Btn7R] * coeff;
		motor[port5] = vexRT[Btn7D] * coeff;
		motor[port6] = vexRT[Btn7L] * coeff;
		motor[port7] = vexRT[Btn8U] * coeff;
		motor[port8] = vexRT[Btn8R] * coeff;
		motor[port9] = vexRT[Btn8D] * coeff;
		motor[port10] = vexRT[Btn8L] * coeff;
	}
}
