#pragma config(Sensor, in2,    liftPot,        sensorPotentiometer)
#pragma config(Motor,  port2,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           lift2,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../lib/motorGroup.c"

motorGroup lift;
int target = 0;

task main() {
	initializeGroup(lift, 2, lift1, lift2);
	addSensor(lift, liftPot);
	setTargetingPIDconsts(lift, 0.4, 0.0, 0.75, 25);
	int prevTarget = target;

	while (true) {
		if (prevTarget != target) {
			setTargetPosition(lift, target);
			prevTarget = target;
		}

		maintainTargetPos(lift);
	}
}
