#pragma config(Sensor, in1,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, in2,    chainPot,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftEnc,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEnc,       sensorQuadEncoder)
#pragma config(Motor,  port1,           LDrive1,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LDrive2,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           mobileGoal1,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           intake,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           chainMotors,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftMotors,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mobileGoal2,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RDrive1,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          RDrive2,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#region config
#define TESTING 0	//0 for normal behavior, 1 for PID testing
//#endregion

//#region positions
enum chainState  { CH_DEF,	INTAKE, SAFE, STACK };	//when chain bar is SAFE, lift can move up and down without colliding with cone stack
int chainPos[] = { 1600,    2400,   1215, 100 };

enum liftState  { L_DEF, L_ZERO, L_MAX, PRELOAD, M_BASE_POS, S_BASE_POS };
int liftPos[] = { 300,   1150,   2000,  1100,    200,        1250 };
//#endregion

//#region setup
#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
#include "..\lib\pd_autoMove.c"
#include "..\lib\buttonTracker.c"
//#endregion

//#region buttons
#define stackBtn					Btn5U
	//#subregion cone count adjustment
#define resetBtn					Btn8U
#define decreaseConesBtn	Btn8D
#define increaseConesBtn	Btn8L
	//#endsubregion
//#endregion

//#region constants
	//#subregion measurements
#define CONE_HEIGHT 2.75
#define LIFT_LEN 11.5
	//#endsubregion
	//#subregion still speeds
#define INTAKE_STILL_SPEED 10
	//#endsubregion
#define INTAKE_DURATION 250	//amount of time rollers activate when intaking/expelling
#define RAD_TO_POT_FCTR 880.1
#define LIFT_OFFSET 150
//#endregion

//#region globals
int numCones = 0; //current number of stacked cones
bool stacking = false;	//whether the robot is currently in the process of stacking
static float heightOffset = sin((liftPos[M_BASE_POS] - liftPos[L_ZERO]) / RAD_TO_POT_FCTR);
float liftAngle, chainAngle;	//the target angles of lift sections during a stack maneuver

motorGroup lift;
motorGroup chainBar;
motorGroup goalIntake;
motorGroup coneIntake;
//#endregion

void pre_auton() {
	bStopTasksBetweenModes = true;

	initializeAutoMovement();

	//configure drive
	initializeDrive(drive, true);
	setDriveMotors(drive, 4, LDrive1, LDrive2, RDrive1, RDrive2);
	/*attachEncoder(drive, leftEnc, LEFT);
	attachEncoder(drive, rightEnc, RIGHT, false, 3.25);
	attachGyro(drive, hyro);*/

	//configure lift
	initializeGroup(lift, 1, liftMotors);
  setTargetingPIDconsts(lift, 0.4, 0.001, 0.8, 25);
	addSensor(lift, liftPot);

	//configure chain bar
	initializeGroup(chainBar, 1, chainMotors);
	setTargetingPIDconsts(chainBar, 0.17, 0.0, 0.4, 25);
	addSensor(chainBar, chainPot);

	//configure mobile goal intake
	initializeGroup(goalIntake, 2, mobileGoal1, mobileGoal2);
	configureButtonInput(goalIntake, Btn8U, Btn8D);

	//configure cone intake
	initializeGroup(coneIntake, 1, intake);
}

//#region lift
void setLiftState(liftState state) {
	setTargetPosition(lift, liftPos[state]);
}
//#endregion

//#region chain bar
void setChainBarState(chainState state) {
	setTargetPosition(chainBar, chainPos[state]);
}
//#endregion

//#region autostacking
void waitForMovementToFinish(bool waitForLift=true, bool waitForChain=true, int timeout=75, float chainMargin=150, float liftMargin=150) {
	long movementTimer = resetTimer();

	while (time(movementTimer) < timeout) {
		if (!errorLessThan(chainBar, chainMargin) && waitForChain ||
				!errorLessThan(lift, liftMargin) && waitForLift)
			movementTimer = resetTimer();
		EndTimeSlice();
	}
}

void stackNewCone() {	//TODO: account for limited range of motion, modulus
	chainAngle = chainPos[STACK];
	liftAngle = limit(RAD_TO_POT_FCTR * asin(CONE_HEIGHT * numCones / 2 / LIFT_LEN + heightOffset) + liftPos[L_ZERO]/*) % (2 * PI)*/,
										liftPos[L_DEF], liftPos[L_MAX]);
	stacking = true;
}

task liftManeuvers() {
	while (true) {
		maintainTargetPos(chainBar);
		maintainTargetPos(lift);
		EndTimeSlice();
	}
}

void stopLiftTargeting() {
	stopTargeting(chainBar);
	stopTargeting(lift);
}

task autoStacking() {
	while (true) {
		while (!stacking) EndTimeSlice();

		//intake cone
		setChainBarState(INTAKE);
		setPower(coneIntake, 127);
		waitForMovementToFinish(false);
		//wait1Msec(INTAKE_DURATION);
		setPower(coneIntake, INTAKE_STILL_SPEED);

		//move to desired location
		setChainBarState(SAFE);
		setTargetPosition(lift, liftAngle+LIFT_OFFSET);

		while (getPosition(lift) < liftAngle) EndTimeSlice();
		setTargetPosition(chainBar, chainAngle);
		waitForMovementToFinish(false);
		setTargetPosition(lift, liftAngle);

		waitForMovementToFinish();

		//expel cone
		setPower(coneIntake, -127);
		setTargetPosition(lift, liftAngle+LIFT_OFFSET);
		wait1Msec(INTAKE_DURATION);
		setChainBarState(CH_DEF);
		setPower(coneIntake, 0);

		//return to ready positions
		numCones++;
		stacking = false;
		setLiftState(L_DEF);
	}
}

void adjustConeCount() {	//change cone count based on user input
	if (newlyPressed(resetBtn))
			numCones = 0;

	if (newlyPressed(increaseConesBtn))
			numCones++;

	if (newlyPressed(decreaseConesBtn))
			if (numCones > 0)
				numCones--;
}
//#endregion

//#region testing
int targets[] = { 0, 0 };	//chain bar, lift
bool abort = false;
bool end = false;

void testPIDs() {
	startTask(liftManeuvers);
	int prevTargets[] = { 0, 0 };

	while (!end) {
		if (targets[0] != prevTargets[0]) {
			setTargetPosition(chainBar, targets[0]);
			prevTargets[0] = targets[0];
		}

		if (targets[1] != prevTargets[1]) {
			setTargetPosition(lift, targets[1]);
			prevTargets[1] = targets[1];
		}

		if (abort) {
			stopLiftTargeting();
			abort = false;
		}

		EndTimeSlice();
	}

	stopTask(liftManeuvers);
}

void handleTesting() {
	if (TESTING == 1)
		testPIDs();
}
//#endregion

//#region autonomous
task autonomous() {

}
//#endregion

task usercontrol() {
	handleTesting();

	startTask(liftManeuvers);
	startTask(autoStacking);

	while (true) {
		if (newlyPressed(stackBtn))
			stackNewCone();

		adjustConeCount();

		takeInput(goalIntake);
		driveRuntime(drive);
	}
}
