#pragma config(Sensor, in1,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  chainEnc,       sensorQuadEncoder)
#pragma config(Motor,  port1,           rd1,           tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rd2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           goal1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           chain,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           cone,          tmotorNone, openLoop)
#pragma config(Motor,  port8,           goal2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ld1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          ld2,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setDrivePower(int left, int right) {
	motor[ld1] = left;
	motor[ld2] = left;
	motor[rd1] = right;
	motor[rd2] = right;
}

void setGoalIntakePower(int power) {
	motor[goal1] = power;
	motor[goal2] = power;
}

task main() {
	int stillSpeed = 15;
  while (true) {
    setDrivePower(vexRT[Ch3], vexRT[Ch2]);
    setGoalIntakePower(127 * (vexRT[Btn7U] - vexRT[Btn7D]));
    motor[chain] = -127 * (vexRT[Btn6U] - vexRT[Btn6D]);

    if (vexRT[Btn8U] == 1) {
    	motor[cone] = 127;
    }
    else if (vexRT[Btn8D] == 1) {
    	motor[cone] = -127;
    }
    else {
    	motor[cone] = 15;
    }

    if (vexRT[Btn5U] == 1) {
    	motor[lift] = 127;
    }
    else if (vexRT[Btn5D] == 1) {
    	motor[lift] = -127;
    }
    else {
    	motor[lift] = stillSpeed;
    }

    /*if (vexRT[Btn7L] == 1) {
    	stillSpeed = 15 - stillSpeed;
    	while (vexRT[Btn7L] == 1);
    	wait1Msec(250);
    }*/
  }
}
