#pragma config(Sensor, in1,    hyro,           sensorGyro)
#pragma config(Sensor, in2,    sidePot,        sensorPotentiometer)
#pragma config(Sensor, in3,    modePot,        sensorPotentiometer)
#pragma config(Sensor, in4,    liftSensor,     sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftEnc,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEnc,       sensorQuadEncoder)
#pragma config(Motor,  port1,           LDrive1,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           lift1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           fb1,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LDrive2,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RDrive1,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           lift2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LDrive3,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           fb2,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           goalMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          RDrive2,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

//#region includes
#include "Vex_Competition_Includes.c"
#include "../lib/parallelDrive.c"
//#endregion

//#region globals
motorGroup lift;
motorGroup goalIntake;
motorGroup fourBar;
parallel_drive drive;
//#endregion


void pre_auton()
{
  bStopTasksBetweenModes = true;

  tMotor LDriveMotors[] = { LDrive1, LDrive2, LDrive3 };
  tMotor RDriveMotors[] = { RDrive1, RDrive2 };
  initializeDrive(drive, 3, LDriveMotors, 2, RDriveMotors);

  tMotor liftMotors[] = { lift1, lift2 };
	initializeGroup(lift, 2, liftMotors, Btn5U, Btn5D, 10);
	configureBtnDependentStillSpeed(lift);

	tMotor goalMotors[] = { goalMotor };
	initializeGroup(goalIntake, 1, goalMotors, Btn7D, Btn7U);
	configureBtnDependentStillSpeed(goalIntake, 15);

	tMotor fbMotors[] = { fb1, fb2 };
	initializeGroup(fourBar, 2, fbMotors, Btn6U, Btn6D, 10, 80);
	configureBtnDependentStillSpeed(fourBar);
}

task autonomous() {
  AutonomousCodePlaceholderForTesting();
}

task usercontrol() {
  while (true) {
    takeInput(lift);
  	takeInput(goalIntake);
  	takeInput(fourBar);
  	driveRuntime(drive);
  }
}
