#pragma config(Sensor, in1,    chainPot,       sensorPotentiometer)
#pragma config(Sensor, in2,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  lGoalPneu,      sensorDigitalOut)
#pragma config(Sensor, dgtl2,  rGoalPneu,      sensorDigitalOut)
#pragma config(Motor,  port1,           lfDriveMot,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rLiftMot,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rfDriveMot,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           lbDriveMot,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           lLiftMot,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           intakeMot,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rChainMot,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rbDriveMot,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           lChainMot,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int liftsetspeed;
#include "..\lib\W ChainBar Functions.c"

void setDrivePower(int left, int right) {
	motor[lfDriveMot] = left;
	motor[lbDriveMot] = left;
	motor[rbDriveMot] = right;
	motor[rfDriveMot] = right;
}

void setLiftPower(int power) {
	motor[lLiftMot] = power;
  motor[rLiftMot] = power;
}

task main() {
	chainRequestedValue = 2600;
  startTask(chainController);

  while(1 == 1) {
  	setDrivePower(vexRT[Ch3], vexRT[Ch2]);

  	if(vexRT[Btn5U] == 1) {
			setLiftPower(127);
      liftsetspeed = 15;
		}
		else if(vexRT[Btn5D] == 1) {
      setLiftPower(127);
      liftsetspeed = -15;
		}
		else {
      setLiftPower(liftsetspeed);
    }

    if(vexRT[Btn6U] == 1) {
    	motor[intakeMot] = 127;
		}
    else if(vexRT[Btn6D] == 1) {
			motor[intakeMot] = -127;
		}
    else {
			motor[intakeMot] = 15;
    }

    if(vexRT[Btn8D] == 1) {
    	chainRequestedValue = 230;
    }
    else if(vexRT[Btn8R] == 1) {
    	chainRequestedValue = 2100;
    }
    else if(vexRT[Btn8U] == 1) {
      chainRequestedValue = 2400;
    }

    if(vexRT[Btn7U] == 1) {
    	SensorValue[lGoalPneu] = 1;
    	SensorValue[rGoalPneu] = 1;
    }
		else if(vexRT[Btn7D] == 1) {
      SensorValue[lGoalPneu] = 0;
      SensorValue[rGoalPneu] = 0;
    }
}
}
